/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    news: News;
    team: Team;
    partners: Partner;
    jobs: Job;
    testimonials: Testimonial;
    'industry-solutions': IndustrySolution;
    'outcome-solutions': OutcomeSolution;
    'plugin-ai-instructions': PluginAiInstruction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'industry-solutions': IndustrySolutionsSelect<false> | IndustrySolutionsSelect<true>;
    'outcome-solutions': OutcomeSolutionsSelect<false> | OutcomeSolutionsSelect<true>;
    'plugin-ai-instructions': PluginAiInstructionsSelect<false> | PluginAiInstructionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'company-overview': CompanyOverview;
    'mission-page': MissionPage;
    'careers-page': CareersPage;
    'platform-overview': PlatformOverview;
    'infrastructure-page': InfrastructurePage;
    'digital-systems-page': DigitalSystemsPage;
    'edge-ai-page': EdgeAiPage;
    'stack-page': StackPage;
    'solutions-overview': SolutionsOverview;
    'impact-overview': ImpactOverview;
    'case-studies-page': CaseStudiesPage;
    'metrics-page': MetricsPage;
    'network-map-page': NetworkMapPage;
    'last-mile-page': LastMilePage;
    'resources-overview': ResourcesOverview;
    'trust-center-page': TrustCenterPage;
    'newsroom-page': NewsroomPage;
    'docs-page': DocsPage;
    'privacy-page': PrivacyPage;
    'terms-page': TermsPage;
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'company-overview': CompanyOverviewSelect<false> | CompanyOverviewSelect<true>;
    'mission-page': MissionPageSelect<false> | MissionPageSelect<true>;
    'careers-page': CareersPageSelect<false> | CareersPageSelect<true>;
    'platform-overview': PlatformOverviewSelect<false> | PlatformOverviewSelect<true>;
    'infrastructure-page': InfrastructurePageSelect<false> | InfrastructurePageSelect<true>;
    'digital-systems-page': DigitalSystemsPageSelect<false> | DigitalSystemsPageSelect<true>;
    'edge-ai-page': EdgeAiPageSelect<false> | EdgeAiPageSelect<true>;
    'stack-page': StackPageSelect<false> | StackPageSelect<true>;
    'solutions-overview': SolutionsOverviewSelect<false> | SolutionsOverviewSelect<true>;
    'impact-overview': ImpactOverviewSelect<false> | ImpactOverviewSelect<true>;
    'case-studies-page': CaseStudiesPageSelect<false> | CaseStudiesPageSelect<true>;
    'metrics-page': MetricsPageSelect<false> | MetricsPageSelect<true>;
    'network-map-page': NetworkMapPageSelect<false> | NetworkMapPageSelect<true>;
    'last-mile-page': LastMilePageSelect<false> | LastMilePageSelect<true>;
    'resources-overview': ResourcesOverviewSelect<false> | ResourcesOverviewSelect<true>;
    'trust-center-page': TrustCenterPageSelect<false> | TrustCenterPageSelect<true>;
    'newsroom-page': NewsroomPageSelect<false> | NewsroomPageSelect<true>;
    'docs-page': DocsPageSelect<false> | DocsPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
    'terms-page': TermsPageSelect<false> | TermsPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  client?: string | null;
  category?: string | null;
  industry?: ('governments' | 'education' | 'ngos' | 'enterprise') | null;
  region?: string | null;
  country?: string | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  publishedAt?: string | null;
  metrics?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  quote?: {
    text?: string | null;
    attribution?: string | null;
    role?: string | null;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  description?: string | null;
  author?: string | null;
  category?: ('press' | 'update' | 'thought-leadership') | null;
  image?: (number | null) | Media;
  featured?: boolean | null;
  publishedAt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  title?: string | null;
  bio?: string | null;
  initials?: string | null;
  image?: (number | null) | Media;
  linkedin?: string | null;
  category?: ('executive' | 'advisory') | null;
  /**
   * For advisors
   */
  affiliation?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  url?: string | null;
  tier?: ('strategic' | 'technology' | 'implementation' | 'institutional') | null;
  /**
   * Type/Category
   */
  type?: string | null;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  department?: ('Engineering' | 'Product' | 'Operations' | 'Sales & Partnerships' | 'People & Finance') | null;
  location?: string | null;
  type?: ('Full-time' | 'Part-time' | 'Contract') | null;
  /**
   * Summary for card listing
   */
  summary?: string | null;
  active?: boolean | null;
  order?: number | null;
  /**
   * Upload Job Description PDF
   */
  sourcePdf?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  attribution: string;
  role?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-solutions".
 */
export interface IndustrySolution {
  id: number;
  title: string;
  headline?: string | null;
  headlineAccent?: string | null;
  description?: string | null;
  ctaPrimary?: {
    text?: string | null;
    href?: string | null;
  };
  ctaSecondary?: {
    text?: string | null;
    href?: string | null;
  };
  benefits?:
    | {
        metric?: string | null;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  caseStudy?: {
    country?: string | null;
    title?: string | null;
    description?: string | null;
    results?:
      | {
          metric: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  whyCards?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaSection?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outcome-solutions".
 */
export interface OutcomeSolution {
  id: number;
  title: string;
  headline?: string | null;
  headlineAccent?: string | null;
  description?: string | null;
  ctaPrimary?: {
    text?: string | null;
    href?: string | null;
  };
  ctaSecondary?: {
    text?: string | null;
    href?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  pillars?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaSection?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions".
 */
export interface PluginAiInstruction {
  id: number;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'schema-path'?: string | null;
  /**
   * Please don't change this unless you're sure of what you're doing
   */
  'field-type'?: ('text' | 'textarea' | 'upload' | 'richText') | null;
  'relation-to'?: string | null;
  'model-id'?: ('GEMINI-text' | 'GEMINI-object' | 'imagen') | null;
  /**
   * Please reload your collection after applying the changes
   */
  disabled?: boolean | null;
  /**
   * Click 'Compose' to run this custom prompt and generate content
   */
  prompt?: string | null;
  images?:
    | {
        /**
         * Please make sure the image is publicly accessible.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  system?: string | null;
  layout?: string | null;
  'GEMINI-text-settings'?: {
    model?:
      | (
          | 'gemini-3-pro-preview'
          | 'gemini-2.5-pro'
          | 'gemini-2.5-flash'
          | 'gemini-2.5-flash-lite'
          | 'gemini-2.0-flash'
          | 'gemini-2.0-flash-lite'
          | 'gemini-flash-latest'
        )
      | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  'GEMINI-object-settings'?: {
    model?:
      | (
          | 'gemini-3-pro-preview'
          | 'gemini-2.5-pro'
          | 'gemini-2.5-flash'
          | 'gemini-2.5-flash-lite'
          | 'gemini-2.0-flash'
          | 'gemini-2.0-flash-lite'
          | 'gemini-flash-latest'
        )
      | null;
    maxTokens?: number | null;
    temperature?: number | null;
    extractAttachments?: boolean | null;
  };
  'imagen-settings'?: {
    model?:
      | (
          | 'imagen-4.0-fast-generate-001'
          | 'imagen-4.0-generate-001'
          | 'imagen-4.0-ultra-generate-001'
          | 'imagen-3.0-generate-002'
        )
      | null;
    aspectRatio?: ('1:1' | '3:4' | '4:3' | '9:16' | '16:9') | null;
    outputMimeType?: ('image/png' | 'image/jpeg') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'industry-solutions';
        value: number | IndustrySolution;
      } | null)
    | ({
        relationTo: 'outcome-solutions';
        value: number | OutcomeSolution;
      } | null)
    | ({
        relationTo: 'plugin-ai-instructions';
        value: number | PluginAiInstruction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  client?: T;
  category?: T;
  industry?: T;
  region?: T;
  country?: T;
  image?: T;
  featured?: T;
  publishedAt?: T;
  metrics?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
        role?: T;
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  author?: T;
  category?: T;
  image?: T;
  featured?: T;
  publishedAt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  initials?: T;
  image?: T;
  linkedin?: T;
  category?: T;
  affiliation?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  tier?: T;
  type?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  type?: T;
  summary?: T;
  active?: T;
  order?: T;
  sourcePdf?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  role?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industry-solutions_select".
 */
export interface IndustrySolutionsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  headlineAccent?: T;
  description?: T;
  ctaPrimary?:
    | T
    | {
        text?: T;
        href?: T;
      };
  ctaSecondary?:
    | T
    | {
        text?: T;
        href?: T;
      };
  benefits?:
    | T
    | {
        metric?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  caseStudy?:
    | T
    | {
        country?: T;
        title?: T;
        description?: T;
        results?:
          | T
          | {
              metric?: T;
              label?: T;
              id?: T;
            };
      };
  whyCards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaSection?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outcome-solutions_select".
 */
export interface OutcomeSolutionsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  headlineAccent?: T;
  description?: T;
  ctaPrimary?:
    | T
    | {
        text?: T;
        href?: T;
      };
  ctaSecondary?:
    | T
    | {
        text?: T;
        href?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  pillars?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaSection?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-ai-instructions_select".
 */
export interface PluginAiInstructionsSelect<T extends boolean = true> {
  'schema-path'?: T;
  'field-type'?: T;
  'relation-to'?: T;
  'model-id'?: T;
  disabled?: T;
  prompt?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  system?: T;
  layout?: T;
  'GEMINI-text-settings'?:
    | T
    | {
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  'GEMINI-object-settings'?:
    | T
    | {
        model?: T;
        maxTokens?: T;
        temperature?: T;
        extractAttachments?: T;
      };
  'imagen-settings'?:
    | T
    | {
        model?: T;
        aspectRatio?: T;
        outputMimeType?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    line1?: string | null;
    line2?: string | null;
    subheadline?: string | null;
    ctaPrimary?: {
      text?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      href?: string | null;
    };
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    partnerLogosTitle?: string | null;
  };
  mission?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    paragraph1?: string | null;
    paragraph2?: string | null;
    linkText?: string | null;
    linkHref?: string | null;
  };
  platform?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    capabilities?:
      | {
          label?: string | null;
          title: string;
          description?: string | null;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  products?: {
    eyebrow?: string | null;
    headline?: string | null;
    description?: string | null;
    items?:
      | {
          name: string;
          tagline?: string | null;
          description?: string | null;
          wireframe?: ('dashboard' | 'mobile') | null;
          id?: string | null;
        }[]
      | null;
  };
  solutions?: {
    eyebrow?: string | null;
    headline?: string | null;
    linkText?: string | null;
    linkHref?: string | null;
    items?:
      | {
          title: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  caseStudies?: {
    eyebrow?: string | null;
    headline?: string | null;
    items?:
      | {
          title: string;
          metric?: string | null;
          metricLabel?: string | null;
          description?: string | null;
          tag?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  impact?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaText?: string | null;
    ctaHref?: string | null;
    metrics?:
      | {
          value?: number | null;
          suffix?: string | null;
          prefix?: string | null;
          label: string;
          format?: ('number' | 'compact') | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    headline?: string | null;
  };
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    contactEmail?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-overview".
 */
export interface CompanyOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  facts?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  story?: {
    eyebrow?: string | null;
    headline?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    linkText?: string | null;
    linkHref?: string | null;
    quote?: {
      text?: string | null;
      name?: string | null;
      role?: string | null;
      initials?: string | null;
    };
  };
  navCards?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  offices?:
    | {
        city: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-page".
 */
export interface MissionPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  mission?: {
    title?: string | null;
    description?: string | null;
  };
  vision?: {
    title?: string | null;
    description?: string | null;
  };
  manifestoQuote?: string | null;
  values?:
    | {
        title: string;
        description?: string | null;
        /**
         * Icon Key
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  milestones?:
    | {
        year?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  teamPreview?:
    | {
        name: string;
        role?: string | null;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page".
 */
export interface CareersPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaPrimary?: {
      text?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      href?: string | null;
    };
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  hiringProcess?:
    | {
        step?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    ctaText?: string | null;
    ctaHref?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-overview".
 */
export interface PlatformOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaPrimary?: {
      text?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      href?: string | null;
    };
  };
  platformAreas?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        metric?: string | null;
        metricLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  architectureLayers?:
    | {
        layer?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure-page".
 */
export interface InfrastructurePage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaPrimary?: {
      text?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      href?: string | null;
    };
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  nodes?:
    | {
        name: string;
        tagline?: string | null;
        description?: string | null;
        specs?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  deploymentModels?:
    | {
        name: string;
        description?: string | null;
        /**
         * Ideal For
         */
        ideal?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-systems-page".
 */
export interface DigitalSystemsPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaPrimary?: {
      text?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      href?: string | null;
    };
  };
  systems?:
    | {
        eyebrow?: string | null;
        name: string;
        description?: string | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  integrationBenefits?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        category?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edge-ai-page".
 */
export interface EdgeAiPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
    ctaPrimary?: {
      text?: string | null;
      href?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      href?: string | null;
    };
  };
  capabilities?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        category?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  howItWorks?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  privacyFeatures?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stack-page".
 */
export interface StackPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  quickStats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  layers?:
    | {
        number?: string | null;
        name: string;
        tagline?: string | null;
        description?: string | null;
        products?:
          | {
              name: string;
              desc?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  designPrinciples?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  layerIntegration?:
    | {
        step?: number | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-overview".
 */
export interface SolutionsOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  industryCards?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  outcomeCards?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-overview".
 */
export interface ImpactOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  navCards?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  regionalHighlights?:
    | {
        region: string;
        description?: string | null;
        story?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonialQuote?: {
    text?: string | null;
    attribution?: string | null;
    role?: string | null;
  };
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-page".
 */
export interface CaseStudiesPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  categoryFilters?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featuredTitle?: string | null;
  allTitle?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics-page".
 */
export interface MetricsPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  primaryMetrics?:
    | {
        value: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  secondaryMetrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  impactStories?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  methodology?: {
    headline?: string | null;
    description?: string | null;
  };
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network-map-page".
 */
export interface NetworkMapPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  liveStats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  regionalDistribution?:
    | {
        region: string;
        nodes?: string | null;
        growth?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  recentDeployments?:
    | {
        location: string;
        nodes?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  networkArchitecture?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "last-mile-page".
 */
export interface LastMilePage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  topicFilters?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutSection?: {
    headline?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-overview".
 */
export interface ResourcesOverview {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  resourceSections?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  quickLinks?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    headline?: string | null;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-center-page".
 */
export interface TrustCenterPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  securityItems?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  complianceItems?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  certifications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        title: string;
        description?: string | null;
        /**
         * Access Level
         */
        access?: string | null;
        id?: string | null;
      }[]
    | null;
  incidentResponse?: {
    responseTime?: string | null;
    monitoring?: string | null;
    notification?: string | null;
  };
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsroom-page".
 */
export interface NewsroomPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  mediaContact?: {
    name?: string | null;
    role?: string | null;
    email?: string | null;
  };
  pressKitItems?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    ctaText?: string | null;
    ctaHref?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-page".
 */
export interface DocsPage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    headlineAccent?: string | null;
    description?: string | null;
  };
  docCategories?:
    | {
        title: string;
        description?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  sdks?:
    | {
        language: string;
        installCommand?: string | null;
        /**
         * Badge/Version
         */
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  supportChannels?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    description?: string | null;
    primaryCta?: {
      text?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      text?: string | null;
      href?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: number;
  title?: string | null;
  lastUpdated?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page".
 */
export interface TermsPage {
  id: number;
  title?: string | null;
  lastUpdated?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  contactEmails?: {
    general?: string | null;
    sales?: string | null;
    press?: string | null;
    security?: string | null;
    careers?: string | null;
    education?: string | null;
    government?: string | null;
    partners?: string | null;
    privacy?: string | null;
    legal?: string | null;
  };
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerQuote?: string | null;
  copyright?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  headerGroups?:
    | {
        label: string;
        href?: string | null;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    secondaryText?: string | null;
    secondaryHref?: string | null;
    primaryText?: string | null;
    primaryHref?: string | null;
  };
  footerGroups?:
    | {
        label: string;
        links?:
          | {
              label: string;
              href: string;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        line1?: T;
        line2?: T;
        subheadline?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        partnerLogosTitle?: T;
      };
  mission?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        paragraph1?: T;
        paragraph2?: T;
        linkText?: T;
        linkHref?: T;
      };
  platform?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        capabilities?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              href?: T;
              id?: T;
            };
      };
  products?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              tagline?: T;
              description?: T;
              wireframe?: T;
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        linkText?: T;
        linkHref?: T;
        items?:
          | T
          | {
              title?: T;
              href?: T;
              id?: T;
            };
      };
  caseStudies?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        items?:
          | T
          | {
              title?: T;
              metric?: T;
              metricLabel?: T;
              description?: T;
              tag?: T;
              id?: T;
            };
      };
  impact?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaText?: T;
        ctaHref?: T;
        metrics?:
          | T
          | {
              value?: T;
              suffix?: T;
              prefix?: T;
              label?: T;
              format?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        contactEmail?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-overview_select".
 */
export interface CompanyOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  facts?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  story?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        linkText?: T;
        linkHref?: T;
        quote?:
          | T
          | {
              text?: T;
              name?: T;
              role?: T;
              initials?: T;
            };
      };
  navCards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        city?: T;
        role?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mission-page_select".
 */
export interface MissionPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  mission?:
    | T
    | {
        title?: T;
        description?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        description?: T;
      };
  manifestoQuote?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  teamPreview?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page_select".
 */
export interface CareersPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  hiringProcess?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        ctaText?: T;
        ctaHref?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-overview_select".
 */
export interface PlatformOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  platformAreas?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        metric?: T;
        metricLabel?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        detail?: T;
        id?: T;
      };
  architectureLayers?:
    | T
    | {
        layer?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "infrastructure-page_select".
 */
export interface InfrastructurePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  nodes?:
    | T
    | {
        name?: T;
        tagline?: T;
        description?: T;
        specs?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  deploymentModels?:
    | T
    | {
        name?: T;
        description?: T;
        ideal?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-systems-page_select".
 */
export interface DigitalSystemsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  systems?:
    | T
    | {
        eyebrow?: T;
        name?: T;
        description?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  integrationBenefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        category?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edge-ai-page_select".
 */
export interface EdgeAiPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              href?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  capabilities?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        category?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  privacyFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stack-page_select".
 */
export interface StackPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  quickStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  layers?:
    | T
    | {
        number?: T;
        name?: T;
        tagline?: T;
        description?: T;
        products?:
          | T
          | {
              name?: T;
              desc?: T;
              id?: T;
            };
        id?: T;
      };
  designPrinciples?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  layerIntegration?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions-overview_select".
 */
export interface SolutionsOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  industryCards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  outcomeCards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-overview_select".
 */
export interface ImpactOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  navCards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  regionalHighlights?:
    | T
    | {
        region?: T;
        description?: T;
        story?: T;
        id?: T;
      };
  testimonialQuote?:
    | T
    | {
        text?: T;
        attribution?: T;
        role?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-page_select".
 */
export interface CaseStudiesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  categoryFilters?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featuredTitle?: T;
  allTitle?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrics-page_select".
 */
export interface MetricsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  primaryMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  secondaryMetrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  impactStories?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  methodology?:
    | T
    | {
        headline?: T;
        description?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "network-map-page_select".
 */
export interface NetworkMapPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  liveStats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  regionalDistribution?:
    | T
    | {
        region?: T;
        nodes?: T;
        growth?: T;
        description?: T;
        id?: T;
      };
  recentDeployments?:
    | T
    | {
        location?: T;
        nodes?: T;
        status?: T;
        id?: T;
      };
  networkArchitecture?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "last-mile-page_select".
 */
export interface LastMilePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  topicFilters?:
    | T
    | {
        text?: T;
        id?: T;
      };
  aboutSection?:
    | T
    | {
        headline?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources-overview_select".
 */
export interface ResourcesOverviewSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  resourceSections?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  quickLinks?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        headline?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-center-page_select".
 */
export interface TrustCenterPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  securityItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  complianceItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        title?: T;
        description?: T;
        access?: T;
        id?: T;
      };
  incidentResponse?:
    | T
    | {
        responseTime?: T;
        monitoring?: T;
        notification?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsroom-page_select".
 */
export interface NewsroomPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  mediaContact?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
      };
  pressKitItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        ctaText?: T;
        ctaHref?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs-page_select".
 */
export interface DocsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineAccent?: T;
        description?: T;
      };
  docCategories?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  sdks?:
    | T
    | {
        language?: T;
        installCommand?: T;
        badge?: T;
        id?: T;
      };
  supportChannels?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              text?: T;
              href?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page_select".
 */
export interface TermsPageSelect<T extends boolean = true> {
  title?: T;
  lastUpdated?: T;
  body?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmails?:
    | T
    | {
        general?: T;
        sales?: T;
        press?: T;
        security?: T;
        careers?: T;
        education?: T;
        government?: T;
        partners?: T;
        privacy?: T;
        legal?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerQuote?: T;
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerGroups?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  headerCta?:
    | T
    | {
        secondaryText?: T;
        secondaryHref?: T;
        primaryText?: T;
        primaryHref?: T;
      };
  footerGroups?:
    | T
    | {
        label?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}